apiVersion: v1
kind: Service
metadata:
  name: sts-headless-991818161
  labels:
    student: "991818161"
spec:
  clusterIP: None
  selector:
    app: sts-web
    student: "991818161"
  ports:
    - port: 80
      targetPort: 80