apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports-pv-991818161
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-991818161
  hostPath:
    path: /tmp/reports-991818161
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc-991818161
  labels:
    student: "991818161"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-991818161